//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CFProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThongKe
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ThongKe()
        {
            this.ChiTietThongKes = new HashSet<ChiTietThongKe>();
        }
    
        public int MaTaiKhoan { get; set; }
        public Nullable<double> TongGiaTri { get; set; }
        public Nullable<double> GiaTriMoiThanhPhan { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietThongKe> ChiTietThongKes { get; set; }
    }
}
